server:
  port: 8082

spring:
  application:
    name: activity-service

  data:
    mongodb:
      uri: mongodb://localhost:27017/fitnessdb

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8181/realms/fitness-app