server:
  port: 8083

spring:
  application:
    name: ai-service

  data:
    mongodb:
      uri: mongodb://localhost:27017/fitnessdb

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8181/realms/fitness-app

gemini:
  api:
    url: https://generativelanguage.googleapis.com/v1beta/models/gemini-3-flash-preview:generateContent
    key: ${GEMINI_API_KEY}